# Generated by Django 3.1.2 on 2020-11-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyer', '0002_answer_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
